name: workloads
project_id: prj_wn6el5cu9dqwktk6t4cv54x8zh
cluster_env: codehornets-cluster-env
compute_config: codehornets-cluster-compute
runtime_env:
  working_dir: .
  upload_path: s3://codehornets/angantakpe/jobs  # <--- CHANGE USERNAME (case-sensitive)
  env_vars:
    GITHUB_USERNAME: angantakpe  # <--- CHANGE USERNAME (case-sensitive)
entrypoint: bash deploy/jobs/workloads.sh
max_retries: 0
